spring.application.name=network-simulator

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/networkdb
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (unchanged)
app.jwt.secret=NetTopoSimSecretKeyForJWTSigningMustBe32CharsMin!!
app.jwt.expiration-ms=86400000
